name: deploy

on: [push]
# on:
#   push:
#     branches:
#       - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10.17"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv venv --python 3.10
        uv sync --group dev
    - name: Build Docs
      run: |
        uv run sphinx-apidoc \
          --ext-autodoc \
          --ext-todo \
          -o docs/source \
          ./src/
        uv run sphinx-build docs/source docs/build/html
    - name: Upload docs
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/build/html
