name: publish

on:
  push:
    tags:
      - 'v*'
    
jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
    
    steps:
      - name: Get tag name
        uses: olegtarasov/get-tag@v2.1.4
        id: tagname
        with:
          tagRegex: "v(.*)"
      - name: Checkout
        uses: actions/checkout@v4 
      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Dependencies
        run: |
          pip install uv
          uv sync --group dev
      - name: Build
        run: |
          uv build
          echo "WHL_FILES=$(ls dist/*.whl)" >> $GITHUB_ENV
      - name: Create GitHub Release
        uses: softprops/action-gh-release
        with:
          files: "dist/shapecheck-${{ steps.tagname.outputs.tag }}-py3-none-any.whl" 
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
